name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'

      - name: Install DEB Packages
        run: sudo apt-get install llvm

      - name: Build
        run: make all

      - name: Test
        run: make test
